### ISSUE TITLE
Where is the map?

### ISSUE THREAD

**Issue by wuc9521** [dorianinc/Phaunos#3]
Hi, I saw in the wiki that there is a feature of **_A map of a the a specific trail is visible on that trails specific page_**, but I couldn't find it when running the project. I have configured the OpenWeather API and Google Maps API. Where can I find the map :)

<img width="1496" alt="image" src="https://github.com/dorianinc/Phaunos/assets/89457423/e8e409ca-21bb-472d-8ccd-a05064773a5d">

**Comment by dorianinc** [comment]
Hi Chentian, thanks for the interest in my app! The way I have it set up,
you're only able go view the map and trail route once you've bookmarked the
trail. From there you go to your bookmarked trails and select the trail and
that should take you there! Let me know if you have any other questions.

There's a slight chance my deployed site is down at the moment I need to
recreate my database on render, if that's the case I can't get to re
deploying it on Monday

**Comment by wuc9521** [comment]
Thank you! I found the map after bookmarking the trail. 👍🏻

**Comment by dorianinc** [comment]
Yeah, and if you want a more detailed trail route I recently found out you
can download them the JSON file off AllTrails!
